=head1 Git::DescribeVersion

A perl module for determining a git repository's current version
based on the C<git-describe> command
which counts commits from the most recent tag.

Use the included L<Dist::Zilla::Plugin::Git::DescribeVersion>
as a L<Version Provider|Dist::Zilla::Role::VersionProvider>
in L<Dist::Zilla> projects,
or put a line like this in the F<Makefile> of other projects:

	VERSION = $(shell perl -MGit::DescribeVersion::App -e run)

See the POD in the module files themselves for more information.

=cut
